language: ruby

before_install:
 -curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
 -curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
 -echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
 -sudo apt-get update
 -sudo apt-get install git-core curl zlib1g-dev build-essential libssl-dev libreadline-dev libyaml-dev libsqlite3-dev sqlite3 libxml2-dev libxslt1-dev libcurl4-openssl-dev python-software-properties libffi-dev nodejs yarn

install:
 -rvm install 2.4.1
 -rvm use 2.4.1
 -gem install bundler
 -bundle install
 -rake db:setup
 -sudo apt-get install libgdbm-dev libncurses5-dev automake libtool bison libffi-dev
 -gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3
 -curl -sSL https://get.rvm.io | bash -s stable
 -source ~/.rvm/scripts/rvm
 -rvm install 2.5.0
 -rvm use 2.5.0 --default
 -ruby -v
