# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU
AWS_ACCESS_KEY: ''
AWS_SECRET_KEY: ''
AWS_BUCKET: ''
AWS_REGION: ''
#development&production:
facebook_client_id: '529985925072978'
facebook_client_secret: 'd76f6eaaa6d11b8a0bd7c1d17849ddae'
google_client_id: '334277817273-j2jeoq27e9lmijpeiqbruseq94i64dh6.apps.googleusercontent.com'
google_client_secret: 'dgdnNbSSYUJnIaYvg7aBWJLf'
#production:
#facebook_client_id: '458489938781377'
#facebook_client_secret: 'baec9d28bc18bddb4c8e457fceb2d4a4'

#For UserMailer production:
#domain_url: 'damp-atoll-07859.herokuapp.com'
#domain_url: 'fashionnxt.herokuapp.com'
domain_url: 'nxtfolio.herokuapp.com'
#For UserMailer:
#gmail_username: 'fashioNTWRKtesting@gmail.com'
#gmail_password: 'test123#'
gmail_username: 'fashionxtllc@gmail.com'
# NXTFolio Spring 2023 : this password is app password generated after enabling 2-step verification
gmail_password: 'yukzwzmegwaxvfbx' 

#Thi i needed for the cucumber tests to visit the correct path
#ELASTICSEARCH_URL: "http://localhost:3000"
